Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/08/2023
Var
// Seção de Declarações das variáveis 
            Area: real
            raio : real
            

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

  escreval ("Digite o valor do raio do circulo")
  leia ( raio )
  
  Area <-  pi * exp(raio,2)

  escreva ("AREA=" ,area    )

Fimalgoritmo