Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/10/2023
Var
// Seção de Declarações das variáveis 

     x, soma : real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreva ("Digite o primeiro numero" )
   leia (x)

    enquanto (x<> 0)faca
     escreval ("Digite outro nùmero" )
      leia (X)
      
    fimenquanto






Fimalgoritmo